=== QbAyyy/SynopticProject/src/Reports/reportSchema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "name": {
            "type": "string",
            "description": "The name of the report."
        },
        "dateCreated": {
            "type": "string",
            "pattern": "^\\d{4}-\\d{2}-\\d{2}$",
            "description": "The date when the report was created (YYYY-MM-DD)."
        },
        "timeCreated": {
            "type": "string",
            "pattern": "^\\d{2}:\\d{2}:\\d{2}$",
            "description": "The time when the report was created (HH:MM:SS)."
        },
        "version": {
            "type": "integer",
            "description": "The version of the report."
        },
        "author": {
            "type": "string",
            "description": "The author of the report."
        },
        "questions": {
            "type": "array",
            "description": "The list of questions in the report.",
            "items": {
                "type": "object",
                "properties": {
                    "text": {
                        "type": "string",
                        "description": "The text of the question."
                    },
                    "answer": {
                        "anyOf": [
                            {
                                "type": "string",
                                "description": "The answer to the question."
                            },
                            {
                                "type": "null",
                                "description": "No answer provided."
                            }
                        ]
                    },
                    "principle":{
                        "type": "string",
                        "description": "The GDPR principle that the question relates to."
                    },
                    "explanation":{
                        "anyOf": [
                            {
                                "type": "string",
                                "description": "The explanation included with the answer"
                            },
                            {
                                "type": "null",
                                "description": "No explanation provided."
                            }
                        ]
                    }
                },
                "required": ["text", "answer", "principle"]
            }
        }
    },
    "required": ["name", "dateCreated", "timeCreated", "version", "author", "questions"]
}

=== QbAyyy/SynopticProject/src/Reports/me.json
{
  "name": "me",
  "dateCreated": "2024-04-21",
  "timeCreated": "16:44:08",
  "version": 1,
  "author": "Me",
  "questions": [
    {
      "text": "Does the privacy policy clearly identify the data controller and provide contact details?",
      "answer": "Yes, the data controller is clearly identified with full contact details.",
      "score": 3,
      "principle": "Transparency"
    },
    {
      "text": "Is the purpose of data processing clearly stated and justified within the policy?",
      "answer": "",
      "score": 0,
      "principle": "Purpose Limitation"
    },
    {
      "text": "Are the specific purposes for processing personal data clearly defined and limited?",
      "answer": "",
      "score": 0,
      "principle": "Purpose Limitation"
    },
    {
      "text": "Is there a clear explanation of how collecting personal data serves these purposes?",
      "answer": "",
      "score": 0,
      "principle": "Transparency"
    },
    {
      "text": "Does the policy ensure that only the necessary personal data for the specified purposes are collected and processed?",
      "answer": "",
      "score": 0,
      "principle": "Data Minimization"
    },
    {
      "text": "Are there mechanisms in place to ensure that personal data is kept accurate and up-to-date?",
      "answer": "",
      "score": 0,
      "principle": "Accuracy"
    },
    {
      "text": "Does the policy specify the retention period for personal data",
      "answer": "",
      "score": 0,
      "principle": "Storage Limitation"
    },
    {
      "text": "What security measures are described to protect personal data against unauthorized or unlawful processing and against accidental loss, destruction, or damage?",
      "answer": "",
      "score": 0,
      "principle": "Security"
    },
    {
      "text": "Does the policy clearly outline the rights of data subjects, including the right to access, correct, delete, or restrict the processing of their personal data?",
      "answer": "",
      "score": 0,
      "principle": "Rights of Data Subjects"
    },
    {
      "text": "Does the policy address the use of automated decision-making and profiling, and if so, does it explain the logic involved and its significance and consequences for the data subject?",
      "answer": "",
      "score": 0,
      "principle": "Automated Decision-Making and Profiling"
    },
    {
      "text": "If the smart cameras use facial recognition or other biometric profiling, how is this addressed in the policy? Are individuals informed about the use of such technologies?",
      "answer": "",
      "score": 0,
      "principle": "Special Categories of Data"
    },
    {
      "text": "How does the policy address the issue of consent for collecting data through smart cameras, particularly in areas where individuals may not have a choice in being observed?",
      "answer": "",
      "score": 0,
      "principle": "Consent"
    },
    {
      "text": "Is there a clear procedure for notifying the supervisory authority and affected data subjects in case of a data breach?",
      "answer": "",
      "score": 0,
      "principle": "Accountability"
    },
    {
      "text": "If a Data Protection Officer is required, does the policy provide details about the DPO, including contact information?",
      "answer": "",
      "score": 0,
      "principle": "Data Protection Officer"
    }
  ]
}

=== QbAyyy/SynopticProject/src/Reports/TestREport.json
{
  "name": "TestREport",
  "dateCreated": "2024-04-23",
  "timeCreated": "16:09:01",
  "version": 1,
  "author": "me",
  "questions": [
    {
      "text": "Does the privacy policy clearly identify the data controller and provide contact details?",
      "answer": "Yes, the data controller is clearly identified with full contact details.",
      "explanation": "",
      "score": 3,
      "principle": "Transparency"
    },
    {
      "text": "Is the purpose of data processing clearly stated and justified within the policy?",
      "answer": "Partially, the purpose is stated but not fully justified or clear.",
      "explanation": "",
      "score": 2,
      "principle": "Purpose Limitation"
    },
    {
      "text": "Are the specific purposes for processing personal data clearly defined and limited?",
      "answer": "Vaguely, purposes are mentioned but not well-defined or limited.",
      "explanation": "",
      "score": 1,
      "principle": "Purpose Limitation"
    },
    {
      "text": "Is there a clear explanation of how collecting personal data serves these purposes?",
      "answer": "No, there is no explanation of how data collection serves the purposes.",
      "explanation": "",
      "score": 0,
      "principle": "Transparency"
    },
    {
      "text": "Does the policy ensure that only the necessary personal data for the specified purposes are collected and processed?",
      "answer": "",
      "explanation": "",
      "score": 0,
      "principle": "Data Minimization"
    },
    {
      "text": "Are there mechanisms in place to ensure that personal data is kept accurate and up-to-date?",
      "answer": "",
      "explanation": "",
      "score": 0,
      "principle": "Accuracy"
    },
    {
      "text": "Does the policy specify the retention period for personal data",
      "answer": "",
      "explanation": "",
      "score": 0,
      "principle": "Storage Limitation"
    },
    {
      "text": "What security measures are described to protect personal data against unauthorized or unlawful processing and against accidental loss, destruction, or damage?",
      "answer": "",
      "explanation": "",
      "score": 0,
      "principle": "Security"
    },
    {
      "text": "Does the policy clearly outline the rights of data subjects, including the right to access, correct, delete, or restrict the processing of their personal data?",
      "answer": "",
      "explanation": "",
      "score": 0,
      "principle": "Rights of Data Subjects"
    },
    {
      "text": "Does the policy address the use of automated decision-making and profiling, and if so, does it explain the logic involved and its significance and consequences for the data subject?",
      "answer": "",
      "explanation": "",
      "score": 0,
      "principle": "Automated Decision-Making and Profiling"
    },
    {
      "text": "If the smart cameras use facial recognition or other biometric profiling, how is this addressed in the policy? Are individuals informed about the use of such technologies?",
      "answer": "",
      "explanation": "",
      "score": 0,
      "principle": "Special Categories of Data"
    },
    {
      "text": "How does the policy address the issue of consent for collecting data through smart cameras, particularly in areas where individuals may not have a choice in being observed?",
      "answer": "",
      "explanation": "",
      "score": 0,
      "principle": "Consent"
    },
    {
      "text": "Is there a clear procedure for notifying the supervisory authority and affected data subjects in case of a data breach?",
      "answer": "",
      "explanation": "",
      "score": 0,
      "principle": "Accountability"
    },
    {
      "text": "If a Data Protection Officer is required, does the policy provide details about the DPO, including contact information?",
      "answer": "",
      "explanation": "",
      "score": 0,
      "principle": "Data Protection Officer"
    }
  ]
}

=== QbAyyy/SynopticProject/src/Reports/Bosch Report.json
{
  "name": "Compliance Report for Bosch Smart cameras",
  "dateCreated": "2024-04-23",
  "timeCreated": "15:04:34",
  "version": 1,
  "author": "Jakub",
  "questions": [
    {
        "text": "Does the privacy policy clearly identify the data controller and provide contact details?",
        "answer": "Yes, the data controller is clearly identified with full contact details.",
        "principle": "Transparency",
        "score": 3,
        "explanation": ""
    },
    {
        "text": "Is the purpose of data processing clearly stated and justified within the policy?",
        "answer": "Yes, the purpose is clearly stated, justified, and aligned with GDPR requirements.",
        "principle": "Purpose Limitation",
        "score": 3,
        "explanation": ""
    },
    {
        "text": "Are the specific purposes for processing personal data clearly defined and limited?",
        "answer": "Yes, specific purposes are clearly defined and limited as per GDPR.",
        "principle": "Purpose Limitation",
        "score": 3,
        "explanation": ""
    },
    {
        "text": "Is there a clear explanation of how collecting personal data serves these purposes?",
        "answer": "Yes, there is a clear explanation of how data collection serves the purposes.",
        "principle": "Transparency",
        "score": 3,
        "explanation": ""
    },
    {
        "text": "Does the policy ensure that only the necessary personal data for the specified purposes are collected and processed?",
        "answer": "Yes, the policy ensures only necessary data for specified purposes are collected.",
        "principle": "Data Minimization",
        "score": 3,
        "explanation": ""
    },
    {
        "text": "Are there mechanisms in place to ensure that personal data is kept accurate and up-to-date?",
        "answer": "Yes, there are clear mechanisms to keep data accurate and up-to-date.",
        "principle": "Accuracy",
        "score": 3,
        "explanation": ""
    },
    {
        "text": "Does the policy specify the retention period for personal data?",
        "answer": "Yes, the retention period is specified and limited to necessary purposes.",
        "principle": "Storage Limitation",
        "score": 3,
        "explanation": ""
    },
    {
        "text": "What security measures are described to protect personal data against unauthorized or unlawful processing and against accidental loss, destruction, or damage?",
        "answer": "Yes, comprehensive security measures are described.",
        "principle": "Security",
        "score": 3,
        "explanation": ""
    },
    {
        "text": "Does the policy clearly outline the rights of data subjects, including the right to access, correct, delete, or restrict the processing of their personal data?",
        "answer": "Yes, the rights are clearly outlined and the process to exercise them is accessible.",
        "principle": "Rights of Data Subjects",
        "score": 3,
        "explanation": ""
    },
    {
        "text": "Does the policy address the use of automated decision-making and profiling, and if so, does it explain the logic involved and its significance and consequences for the data subject?",
        "answer": "Yes, it's clearly addressed with detailed explanations of the logic and significance.",
        "principle": "Automated Decision-Making and Profiling",
        "score": 3,
        "explanation": ""
    },
    {
        "text": "If the smart cameras use facial recognition or other biometric profiling, how is this addressed in the policy? Are individuals informed about the use of such technologies?",
        "answer": "Yes, the use is clearly addressed, with detailed policies and individual notifications.",
        "principle": "Special Categories of Data",
        "score": 3,
        "explanation": ""
    },
    {
        "text": "How does the policy address the issue of consent for collecting data through smart cameras, particularly in areas where individuals may not have a choice in being observed?",
        "answer": "Yes, the policy clearly addresses consent with a clear withdrawal process.",
        "principle": "Consent",
        "score": 3,
        "explanation": ""
    },
    {
        "text": "Is there a clear procedure for notifying the supervisory authority and affected data subjects in case of a data breach?",
        "answer": "Yes, there is a clear procedure for notification of breaches.",
        "principle": "Accountability",
        "score": 3,
        "explanation": ""
    },
    {
        "text": "If a Data Protection Officer is required, does the policy provide details about the DPO, including contact information?",
        "answer": "Yes, the DPO is clearly detailed with contact information.",
        "principle": "Data Protection Officer",
        "score": 3,
        "explanation": ""
    }
]
}

=== QbAyyy/SynopticProject/src/Reports/Eufy Report.json
{
  "name": "Proper Good Report",
  "dateCreated": "2024-04-21",
  "timeCreated": "19:27:33",
  "version": 1,
  "author": "The man on the moon",
  "questions": [
    {
      "text": "Does the privacy policy clearly identify the data controller and provide contact details?",
      "answer": "Yes, the data controller is clearly identified with full contact details.",
      "explanation": "",
      "score": 3,
      "principle": "Transparency"
    },
    {
      "text": "Is the purpose of data processing clearly stated and justified within the policy?",
      "answer": "Partially, the purpose is stated but not fully justified or clear.",
      "explanation": "Beans Meanz heinz ",
      "score": 2,
      "principle": "Purpose Limitation"
    },
    {
      "text": "Are the specific purposes for processing personal data clearly defined and limited?",
      "answer": "No, purposes are not defined or limited.",
      "explanation": "Beaner",
      "score": 0,
      "principle": "Purpose Limitation"
    },
    {
      "text": "Is there a clear explanation of how collecting personal data serves these purposes?",
      "answer": "Vaguely, the explanation of data collection is incomplete or unclear.",
      "explanation": "Cheezit",
      "score": 1,
      "principle": "Transparency"
    },
    {
      "text": "Does the policy ensure that only the necessary personal data for the specified purposes are collected and processed?",
      "answer": "No, there is no mention of data minimization.",
      "explanation": "",
      "score": 0,
      "principle": "Data Minimization"
    },
    {
      "text": "Are there mechanisms in place to ensure that personal data is kept accurate and up-to-date?",
      "answer": "No, there are no mechanisms mentioned for ensuring data accuracy.",
      "explanation": "",
      "score": 0,
      "principle": "Accuracy"
    },
    {
      "text": "Does the policy specify the retention period for personal data",
      "answer": "No, the retention period is not specified or limited.",
      "explanation": "",
      "score": 0,
      "principle": "Storage Limitation"
    },
    {
      "text": "What security measures are described to protect personal data against unauthorized or unlawful processing and against accidental loss, destruction, or damage?",
      "answer": "No, there is no mention of security measures.",
      "explanation": "",
      "score": 0,
      "principle": "Security"
    },
    {
      "text": "Does the policy clearly outline the rights of data subjects, including the right to access, correct, delete, or restrict the processing of their personal data?",
      "answer": "No, the rights are not clearly outlined or the process is not mentioned.",
      "explanation": "",
      "score": 0,
      "principle": "Rights of Data Subjects"
    },
    {
      "text": "Does the policy address the use of automated decision-making and profiling, and if so, does it explain the logic involved and its significance and consequences for the data subject?",
      "answer": "No, there is no mention of automated decision-making or profiling.",
      "explanation": "",
      "score": 0,
      "principle": "Automated Decision-Making and Profiling"
    },
    {
      "text": "If the smart cameras use facial recognition or other biometric profiling, how is this addressed in the policy? Are individuals informed about the use of such technologies?",
      "answer": "No, there is no mention or clear policy on the use of such technologies.",
      "explanation": "",
      "score": 0,
      "principle": "Special Categories of Data"
    },
    {
      "text": "How does the policy address the issue of consent for collecting data through smart cameras, particularly in areas where individuals may not have a choice in being observed?",
      "answer": "No, there is no mention of consent or the process for obtaining/withdrawing it.",
      "explanation": "",
      "score": 0,
      "principle": "Consent"
    },
    {
      "text": "Is there a clear procedure for notifying the supervisory authority and affected data subjects in case of a data breach?",
      "answer": "Yes, there is a clear procedure for notification of breaches.",
      "explanation": "",
      "score": 3,
      "principle": "Accountability"
    },
    {
      "text": "If a Data Protection Officer is required, does the policy provide details about the DPO, including contact information?",
      "answer": "Yes, the DPO is clearly detailed with contact information.",
      "explanation": "",
      "score": 3,
      "principle": "Data Protection Officer"
    }
  ]
}
